version: "3"

services:
  node:
    image: "node:12.17.0"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    expose:
      - "3000"
    command: "npm run start"

  nginx:
    image: nginx:1.18-alpine
    tty: true
    ports:
      - "80:80"
    volumes:
      - .:/var/www/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default
    depends_on:
      - node

networks:
  default:
    driver: bridge